config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
  get "tasks/:id", to: "tasks#show", as: :task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end
  
  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
    
  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/8f1eab0014.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed, {}, true, false  %>
  <%= f.submit %>
<% end %>
<%= link_to 'Back to task', task_path(@task) %>

app/views/tasks/index.html.erb
<h1>My task</h1>
<ul>
  <% @tasks.each do |task|%>
    <li>
      <% if task.completed %>
      <i class="far fa-check-square"></i>
      <% else %>
      <i class="far fa-square"></i>
      <% end %>
      <%= link_to task.title, task_path(task) %>
      <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fas fa-dumpster-fire"></i>
      <% end %>
    </li>
  <% end %>
  <%= link_to "Add new task", tasks_new_path %>
</ul>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
  <%= link_to 'Back to list', tasks_path %>
<% end %>

app/views/tasks/show.html.erb
<h1><%=@task.title %></h1>
<p>
  <% if @task.completed %>
    <i class="far fa-check-square"></i>
  <% else %>
    <i class="far fa-square"></i>
  <% end %>
  <%= @task.details %>
  
  <%= link_to 'Edit task', edit_path %>
  <%= link_to 'Back to list', tasks_path %>
</p>